package proxy

import (
	"sync"

	proxyinfra "github.com/websoft9/appos/backend/infra/proxy"
)

var (
	defaultRegistryOnce sync.Once
	defaultRegistry     *proxyinfra.Registry
	defaultRegistryErr  error
)

func DefaultRegistry() (*proxyinfra.Registry, error) {
	defaultRegistryOnce.Do(func() {
		defaultRegistry, defaultRegistryErr = proxyinfra.NewRegistry(defaultDefinitions()...)
	})
	return defaultRegistry, defaultRegistryErr
}

func defaultDefinitions() []proxyinfra.Definition {
	return []proxyinfra.Definition{
		{
			Key:            "http.global",
			Title:          "HTTP Policies",
			Description:    "Policy anchor for AppOS local outbound HTTP(S) traffic.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"http", "local", "policy"},
		},
		{
			Key:            "http.general",
			Title:          "General HTTP",
			Description:    "General AppOS local outbound HTTP(S) requests.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "http.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"http", "local", "general"},
		},
		{
			Key:            "http.ai",
			Title:          "AI HTTP",
			Description:    "AI provider outbound HTTP(S) requests.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "http.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"ai", "http", "local"},
		},
		{
			Key:            "download.global",
			Title:          "Download Policies",
			Description:    "Policy anchor for AppOS local download workflows.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"download", "local", "policy"},
		},
		{
			Key:            "download.general",
			Title:          "General Downloads",
			Description:    "AppOS local file and asset downloads.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "download.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"download", "http", "local"},
		},
		{
			Key:            "git.global",
			Title:          "Git Policies",
			Description:    "Policy anchor for AppOS local git network operations.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterEnv,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"git", "local", "policy", "subprocess"},
		},
		{
			Key:            "git.general",
			Title:          "General Git",
			Description:    "AppOS local git clone, fetch, and remote inspection workflows.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "git.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterEnv,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"git", "local", "subprocess"},
		},
		{
			Key:            "remote_shell.global",
			Title:          "Remote Shell",
			Description:    "Remote shell subprocess egress policy.",
			Location:       proxyinfra.LocationRemote,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterEnv,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"remote", "shell", "subprocess"},
		},
		{
			Key:            "remote_runtime.global",
			Title:          "Remote Runtime",
			Description:    "Remote Docker and runtime egress policy.",
			Location:       proxyinfra.LocationRemote,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterEnv,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeDisabled,
			Tags:           []string{"docker", "remote", "runtime", "subprocess"},
		},
		{
			Key:            "control_plane.global",
			Title:          "Control Plane",
			Description:    "Policy anchor for direct-only control-plane channels.",
			Location:       proxyinfra.LocationRemote,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterDialer,
			TrafficClass:   proxyinfra.TrafficClassControlPlane,
			Support:        proxyinfra.SupportBypassOnly,
			DefaultMode:    proxyinfra.ModeDisabled,
			Tags:           []string{"control-plane", "remote"},
		},
		{
			Key:            "control_plane.ssh",
			Title:          "SSH Control Channel",
			Description:    "Direct-only SSH control channel used to establish remote shell sessions.",
			Location:       proxyinfra.LocationRemote,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "control_plane.global",
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterDialer,
			TrafficClass:   proxyinfra.TrafficClassControlPlane,
			Support:        proxyinfra.SupportBypassOnly,
			DefaultMode:    proxyinfra.ModeDisabled,
			Tags:           []string{"control-plane", "remote", "ssh"},
		},
		{
			Key:            "control_plane.sftp",
			Title:          "SFTP Control Channel",
			Description:    "Direct-only SFTP control path used by remote file browsing and transfer.",
			Location:       proxyinfra.LocationRemote,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "control_plane.global",
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterDialer,
			TrafficClass:   proxyinfra.TrafficClassControlPlane,
			Support:        proxyinfra.SupportBypassOnly,
			DefaultMode:    proxyinfra.ModeDisabled,
			Tags:           []string{"control-plane", "remote", "sftp"},
		},
		{
			Key:            "control_plane.reachability",
			Title:          "Reachability Probe",
			Description:    "Direct-only reachability probe used before remote shell workflows are opened.",
			Location:       proxyinfra.LocationRemote,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "control_plane.global",
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterDialer,
			TrafficClass:   proxyinfra.TrafficClassControlPlane,
			Support:        proxyinfra.SupportBypassOnly,
			DefaultMode:    proxyinfra.ModeDisabled,
			Tags:           []string{"control-plane", "probe", "remote"},
		},
	}
}
