package proxy

import (
	"sync"

	proxyinfra "github.com/websoft9/appos/backend/infra/proxy"
)

var (
	defaultRegistryOnce sync.Once
	defaultRegistry     *proxyinfra.Registry
	defaultRegistryErr  error
)

func DefaultRegistry() (*proxyinfra.Registry, error) {
	defaultRegistryOnce.Do(func() {
		defaultRegistry, defaultRegistryErr = proxyinfra.NewRegistry(defaultDefinitions()...)
	})
	return defaultRegistry, defaultRegistryErr
}

func defaultDefinitions() []proxyinfra.Definition {
	return []proxyinfra.Definition{
		{
			Key:            "ai_providers.global",
			Title:          "AI Providers",
			Description:    "Module-level outbound AI provider traffic policy.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeFallback,
			AllowFallback:  true,
			Tags:           []string{"ai", "llm", "public", "retry-safe"},
		},
		{
			Key:            "git.global",
			Title:          "Git",
			Description:    "Module-level git proxy policy anchor.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterEnv,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"git", "subprocess"},
		},
		{
			Key:            "git.fetch_remote",
			Title:          "Git Fetch Remote",
			Description:    "Remote git fetch and clone-style subprocess access.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "git.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterEnv,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeFallback,
			AllowFallback:  true,
			Tags:           []string{"git", "retry-safe", "subprocess"},
		},
		{
			Key:            "feeds.global",
			Title:          "Feeds",
			Description:    "Module-level feed proxy policy anchor.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeFallback,
			AllowFallback:  true,
			Tags:           []string{"feeds", "read", "retry-safe"},
		},
		{
			Key:            "feeds.fetch_source",
			Title:          "Feed Fetch Source",
			Description:    "Fetch remote feed source content.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "feeds.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeFallback,
			AllowFallback:  true,
			Tags:           []string{"feeds", "read", "retry-safe"},
		},
		{
			Key:            "feeds.fetch_favicon",
			Title:          "Feed Fetch Favicon",
			Description:    "Fetch remote feed favicon and icon assets.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "feeds.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeFallback,
			AllowFallback:  true,
			Tags:           []string{"feeds", "favicon", "read", "retry-safe"},
		},
		{
			Key:            "space.global",
			Title:          "Space",
			Description:    "Module-level space proxy policy anchor.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"space"},
		},
		{
			Key:            "space.fetch_file",
			Title:          "Space Fetch File",
			Description:    "Remote file fetches initiated from space workflows.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "space.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeFallback,
			AllowFallback:  true,
			Tags:           []string{"read", "retry-safe", "space"},
		},
		{
			Key:            "deploy.global",
			Title:          "Deploy",
			Description:    "Module-level deployment proxy policy anchor.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterEnv,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"deploy", "subprocess"},
		},
		{
			Key:            "deploy.git_fetch",
			Title:          "Deploy Git Fetch",
			Description:    "Git network actions executed during deployment workflows.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "deploy.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterEnv,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeFallback,
			AllowFallback:  true,
			Tags:           []string{"deploy", "git", "retry-safe", "subprocess"},
		},
		{
			Key:            "deploy.asset_download",
			Title:          "Deploy Asset Download",
			Description:    "External file downloads used by deployment flows.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "deploy.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeFallback,
			AllowFallback:  true,
			Tags:           []string{"deploy", "download", "retry-safe"},
		},
		{
			Key:            "external_services.global",
			Title:          "External Services",
			Description:    "Module-level external services proxy policy anchor.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"connectors", "external-services"},
		},
		{
			Key:            "external_services.outbound_http",
			Title:          "External Services Outbound HTTP",
			Description:    "Connector-backed outbound HTTP actions.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "external_services.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"connectors", "external-services", "http"},
		},
		{
			Key:            "runtime_instances.global",
			Title:          "Runtime Instances",
			Description:    "Module-level runtime instance proxy policy anchor.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"instances", "runtime"},
		},
		{
			Key:            "runtime_instances.http_check",
			Title:          "Runtime Instance HTTP Check",
			Description:    "HTTP-based instance checks that may safely fall back to proxy.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "runtime_instances.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeFallback,
			AllowFallback:  true,
			Tags:           []string{"instances", "probe", "retry-safe"},
		},
		{
			Key:            "platform_accounts.global",
			Title:          "Platform Accounts",
			Description:    "Module-level platform account proxy policy anchor.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"accounts", "platform"},
		},
		{
			Key:            "platform_accounts.outbound_http",
			Title:          "Platform Accounts Outbound HTTP",
			Description:    "Platform account outbound HTTP actions.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "platform_accounts.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"accounts", "http", "platform"},
		},
		{
			Key:            "software_inventory.global",
			Title:          "Software Inventory",
			Description:    "Module-level software inventory proxy policy anchor.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeAlways,
			Tags:           []string{"inventory", "software"},
		},
		{
			Key:            "software_inventory.http_probe",
			Title:          "Software Inventory HTTP Probe",
			Description:    "Read-only HTTP probes for inventory detection.",
			Location:       proxyinfra.LocationLocal,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "software_inventory.global",
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterHTTPClient,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeFallback,
			AllowFallback:  true,
			Tags:           []string{"inventory", "read", "retry-safe", "software"},
		},
		{
			Key:            "servers.global",
			Title:          "Servers",
			Description:    "Workspace-wide proxy policy for remote server shell and subprocess operations.",
			Location:       proxyinfra.LocationRemote,
			Scope:          proxyinfra.ScopeModule,
			AllowDirectUse: true,
			Adapter:        proxyinfra.AdapterEnv,
			TrafficClass:   proxyinfra.TrafficClassPublicEgress,
			Support:        proxyinfra.SupportProxyCapable,
			DefaultMode:    proxyinfra.ModeFallback,
			AllowFallback:  true,
			Tags:           []string{"remote", "servers", "shell", "subprocess", "retry-safe"},
		},
		{
			Key:            "servers.ssh_control",
			Title:          "SSH Control Channel",
			Description:    "Direct-only SSH control channel used to establish remote shell sessions.",
			Location:       proxyinfra.LocationRemote,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "servers.global",
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterDialer,
			TrafficClass:   proxyinfra.TrafficClassControlPlane,
			Support:        proxyinfra.SupportBypassOnly,
			DefaultMode:    proxyinfra.ModeDisabled,
			Tags:           []string{"remote", "servers", "ssh", "control-plane"},
		},
		{
			Key:            "servers.sftp_control",
			Title:          "SFTP Control Channel",
			Description:    "Direct-only SFTP control path used by remote file browsing and transfer.",
			Location:       proxyinfra.LocationRemote,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "servers.global",
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterDialer,
			TrafficClass:   proxyinfra.TrafficClassControlPlane,
			Support:        proxyinfra.SupportBypassOnly,
			DefaultMode:    proxyinfra.ModeDisabled,
			Tags:           []string{"remote", "servers", "sftp", "control-plane"},
		},
		{
			Key:            "servers.reachability_probe",
			Title:          "Server Reachability Probe",
			Description:    "Direct-only server reachability probe used before shell workflows are opened.",
			Location:       proxyinfra.LocationRemote,
			Scope:          proxyinfra.ScopeAction,
			ModuleKey:      "servers.global",
			AllowDirectUse: false,
			Adapter:        proxyinfra.AdapterDialer,
			TrafficClass:   proxyinfra.TrafficClassControlPlane,
			Support:        proxyinfra.SupportBypassOnly,
			DefaultMode:    proxyinfra.ModeDisabled,
			Tags:           []string{"remote", "servers", "probe", "control-plane"},
		},
	}
}
