package egress

import "sync"

var (
	defaultRegistryOnce sync.Once
	defaultRegistry     *Registry
	defaultRegistryErr  error
)

func DefaultRegistry() (*Registry, error) {
	defaultRegistryOnce.Do(func() {
		defaultRegistry, defaultRegistryErr = NewRegistry(defaultDefinitions()...)
	})
	return defaultRegistry, defaultRegistryErr
}

func defaultDefinitions() []Definition {
	return []Definition{
		{
			Key:            "http.global",
			Title:          "HTTP Policies",
			Description:    "Policy anchor for AppOS local outbound HTTP(S) traffic.",
			Location:       LocationLocal,
			Scope:          ScopeModule,
			AllowDirectUse: false,
			Adapter:        AdapterHTTPClient,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeAlways,
			Tags:           []string{"http", "local", "policy"},
		},
		{
			Key:            "http.general",
			Title:          "General HTTP",
			Description:    "General AppOS local outbound HTTP(S) requests.",
			Location:       LocationLocal,
			Scope:          ScopeAction,
			ModuleKey:      "http.global",
			AllowDirectUse: true,
			Adapter:        AdapterHTTPClient,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeAlways,
			Tags:           []string{"http", "local", "general"},
		},
		{
			Key:            "http.ai",
			Title:          "AI HTTP",
			Description:    "AI provider outbound HTTP(S) requests.",
			Location:       LocationLocal,
			Scope:          ScopeAction,
			ModuleKey:      "http.global",
			AllowDirectUse: true,
			Adapter:        AdapterHTTPClient,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeAlways,
			Tags:           []string{"ai", "http", "local"},
		},
		{
			Key:            "download.global",
			Title:          "Download Policies",
			Description:    "Policy anchor for AppOS local download workflows.",
			Location:       LocationLocal,
			Scope:          ScopeModule,
			AllowDirectUse: false,
			Adapter:        AdapterHTTPClient,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeAlways,
			Tags:           []string{"download", "local", "policy"},
		},
		{
			Key:            "download.general",
			Title:          "General Downloads",
			Description:    "AppOS local file and asset downloads.",
			Location:       LocationLocal,
			Scope:          ScopeAction,
			ModuleKey:      "download.global",
			AllowDirectUse: true,
			Adapter:        AdapterHTTPClient,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeAlways,
			Tags:           []string{"download", "http", "local"},
		},
		{
			Key:            "git.global",
			Title:          "Git Policies",
			Description:    "Policy anchor for AppOS local git network operations.",
			Location:       LocationLocal,
			Scope:          ScopeModule,
			AllowDirectUse: false,
			Adapter:        AdapterEnv,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeAlways,
			Tags:           []string{"git", "local", "policy", "subprocess"},
		},
		{
			Key:            "git.general",
			Title:          "General Git",
			Description:    "AppOS local git clone, fetch, and remote inspection workflows.",
			Location:       LocationLocal,
			Scope:          ScopeAction,
			ModuleKey:      "git.global",
			AllowDirectUse: true,
			Adapter:        AdapterEnv,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeAlways,
			Tags:           []string{"git", "local", "subprocess"},
		},
		{
			Key:            "remote_shell.global",
			Title:          "Remote Shell",
			Description:    "Remote shell subprocess egress policy.",
			Location:       LocationRemote,
			Scope:          ScopeModule,
			AllowDirectUse: false,
			Adapter:        AdapterEnv,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeAlways,
			Tags:           []string{"remote", "shell", "subprocess"},
		},
		{
			Key:            "remote_shell.env",
			Title:          "Remote Shell Env",
			Description:    "Remote shell startup environment injection surface.",
			Location:       LocationRemote,
			Scope:          ScopeAction,
			ModuleKey:      "remote_shell.global",
			AllowDirectUse: true,
			Adapter:        AdapterEnv,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeAlways,
			Tags:           []string{"remote", "shell", "env"},
		},
		{
			Key:            "remote_shell.tunnel_http",
			Title:          "Remote Shell Tunnel HTTP",
			Description:    "AppOS-side HTTP forwarding for reverse-tunnel shell egress.",
			Location:       LocationRemote,
			Scope:          ScopeAction,
			ModuleKey:      "remote_shell.global",
			AllowDirectUse: true,
			Adapter:        AdapterHTTPClient,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeAlways,
			Tags:           []string{"remote", "shell", "http", "tunnel"},
		},
		{
			Key:            "remote_shell.tunnel_dialer",
			Title:          "Remote Shell Tunnel Dialer",
			Description:    "AppOS-side raw dialing for reverse-tunnel shell egress.",
			Location:       LocationRemote,
			Scope:          ScopeAction,
			ModuleKey:      "remote_shell.global",
			AllowDirectUse: true,
			Adapter:        AdapterDialer,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeAlways,
			Tags:           []string{"remote", "shell", "dialer", "tunnel"},
		},
		{
			Key:            "remote_runtime.global",
			Title:          "Remote Runtime",
			Description:    "Remote Docker and runtime egress policy.",
			Location:       LocationRemote,
			Scope:          ScopeModule,
			AllowDirectUse: true,
			Adapter:        AdapterEnv,
			TrafficClass:   TrafficClassPublicEgress,
			Support:        SupportProxyCapable,
			DefaultMode:    ModeDisabled,
			Tags:           []string{"docker", "remote", "runtime", "subprocess"},
		},
		{
			Key:            "control_plane.global",
			Title:          "Control Plane",
			Description:    "Policy anchor for direct-only control-plane channels.",
			Location:       LocationRemote,
			Scope:          ScopeModule,
			AllowDirectUse: false,
			Adapter:        AdapterDialer,
			TrafficClass:   TrafficClassControlPlane,
			Support:        SupportBypassOnly,
			DefaultMode:    ModeDisabled,
			Tags:           []string{"control-plane", "remote"},
		},
		{
			Key:            "control_plane.ssh",
			Title:          "SSH Control Channel",
			Description:    "Direct-only SSH control channel used to establish remote shell sessions.",
			Location:       LocationRemote,
			Scope:          ScopeAction,
			ModuleKey:      "control_plane.global",
			AllowDirectUse: false,
			Adapter:        AdapterDialer,
			TrafficClass:   TrafficClassControlPlane,
			Support:        SupportBypassOnly,
			DefaultMode:    ModeDisabled,
			Tags:           []string{"control-plane", "remote", "ssh"},
		},
		{
			Key:            "control_plane.sftp",
			Title:          "SFTP Control Channel",
			Description:    "Direct-only SFTP control path used by remote file browsing and transfer.",
			Location:       LocationRemote,
			Scope:          ScopeAction,
			ModuleKey:      "control_plane.global",
			AllowDirectUse: false,
			Adapter:        AdapterDialer,
			TrafficClass:   TrafficClassControlPlane,
			Support:        SupportBypassOnly,
			DefaultMode:    ModeDisabled,
			Tags:           []string{"control-plane", "remote", "sftp"},
		},
		{
			Key:            "control_plane.reachability",
			Title:          "Reachability Probe",
			Description:    "Direct-only reachability probe used before remote shell workflows are opened.",
			Location:       LocationRemote,
			Scope:          ScopeAction,
			ModuleKey:      "control_plane.global",
			AllowDirectUse: false,
			Adapter:        AdapterDialer,
			TrafficClass:   TrafficClassControlPlane,
			Support:        SupportBypassOnly,
			DefaultMode:    ModeDisabled,
			Tags:           []string{"control-plane", "probe", "remote"},
		},
	}
}
