/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSetupRouteImport } from './routes/_app/setup'
import { Route as AppResetPasswordRouteImport } from './routes/_app/reset-password'
import { Route as AppRegisterRouteImport } from './routes/_app/register'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppForgotPasswordRouteImport } from './routes/_app/forgot-password'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppAuthSpaceRouteImport } from './routes/_app/_auth/space'
import { Route as AppAuthServicesRouteImport } from './routes/_app/_auth/services'
import { Route as AppAuthProfileRouteImport } from './routes/_app/_auth/profile'
import { Route as AppAuthDockerRouteImport } from './routes/_app/_auth/docker'
import { Route as AppAuthDashboardRouteImport } from './routes/_app/_auth/dashboard'
import { Route as AppAuthAuditRouteImport } from './routes/_app/_auth/audit'
import { Route as AppAuthSuperuserRouteImport } from './routes/_app/_auth/_superuser'
import { Route as AppAuthStoreIndexRouteImport } from './routes/_app/_auth/store/index'
import { Route as AppAuthResourcesIndexRouteImport } from './routes/_app/_auth/resources/index'
import { Route as AppAuthResourcesServersRouteImport } from './routes/_app/_auth/resources/servers'
import { Route as AppAuthResourcesSecretsRouteImport } from './routes/_app/_auth/resources/secrets'
import { Route as AppAuthResourcesScriptsRouteImport } from './routes/_app/_auth/resources/scripts'
import { Route as AppAuthResourcesIntegrationsRouteImport } from './routes/_app/_auth/resources/integrations'
import { Route as AppAuthResourcesGroupsRouteImport } from './routes/_app/_auth/resources/groups'
import { Route as AppAuthResourcesEnvGroupsRouteImport } from './routes/_app/_auth/resources/env-groups'
import { Route as AppAuthResourcesDatabasesRouteImport } from './routes/_app/_auth/resources/databases'
import { Route as AppAuthResourcesCloudAccountsRouteImport } from './routes/_app/_auth/resources/cloud-accounts'
import { Route as AppAuthResourcesCertificatesRouteImport } from './routes/_app/_auth/resources/certificates'
import { Route as AppAuthSuperuserSettingsRouteImport } from './routes/_app/_auth/_superuser/settings'
import { Route as AppAuthSuperuserLogsRouteImport } from './routes/_app/_auth/_superuser/logs'
import { Route as AppAuthSuperuserIacRouteImport } from './routes/_app/_auth/_superuser/iac'
import { Route as AppAuthResourcesGroupsIndexRouteImport } from './routes/_app/_auth/resources/groups.index'
import { Route as AppAuthSuperuserUsersIndexRouteImport } from './routes/_app/_auth/_superuser/users/index'
import { Route as AppAuthResourcesGroupsIdRouteImport } from './routes/_app/_auth/resources/groups.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppResetPasswordRoute = AppResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthSpaceRoute = AppAuthSpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthServicesRoute = AppAuthServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthProfileRoute = AppAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDockerRoute = AppAuthDockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardRoute = AppAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthAuditRoute = AppAuthAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthSuperuserRoute = AppAuthSuperuserRouteImport.update({
  id: '/_superuser',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthStoreIndexRoute = AppAuthStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthResourcesIndexRoute = AppAuthResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthResourcesServersRoute = AppAuthResourcesServersRouteImport.update({
  id: '/resources/servers',
  path: '/resources/servers',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthResourcesSecretsRoute = AppAuthResourcesSecretsRouteImport.update({
  id: '/resources/secrets',
  path: '/resources/secrets',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthResourcesScriptsRoute = AppAuthResourcesScriptsRouteImport.update({
  id: '/resources/scripts',
  path: '/resources/scripts',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthResourcesIntegrationsRoute =
  AppAuthResourcesIntegrationsRouteImport.update({
    id: '/resources/integrations',
    path: '/resources/integrations',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthResourcesGroupsRoute = AppAuthResourcesGroupsRouteImport.update({
  id: '/resources/groups',
  path: '/resources/groups',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthResourcesEnvGroupsRoute =
  AppAuthResourcesEnvGroupsRouteImport.update({
    id: '/resources/env-groups',
    path: '/resources/env-groups',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthResourcesDatabasesRoute =
  AppAuthResourcesDatabasesRouteImport.update({
    id: '/resources/databases',
    path: '/resources/databases',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthResourcesCloudAccountsRoute =
  AppAuthResourcesCloudAccountsRouteImport.update({
    id: '/resources/cloud-accounts',
    path: '/resources/cloud-accounts',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthResourcesCertificatesRoute =
  AppAuthResourcesCertificatesRouteImport.update({
    id: '/resources/certificates',
    path: '/resources/certificates',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthSuperuserSettingsRoute =
  AppAuthSuperuserSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthSuperuserRoute,
  } as any)
const AppAuthSuperuserLogsRoute = AppAuthSuperuserLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAuthSuperuserRoute,
} as any)
const AppAuthSuperuserIacRoute = AppAuthSuperuserIacRouteImport.update({
  id: '/iac',
  path: '/iac',
  getParentRoute: () => AppAuthSuperuserRoute,
} as any)
const AppAuthResourcesGroupsIndexRoute =
  AppAuthResourcesGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthResourcesGroupsRoute,
  } as any)
const AppAuthSuperuserUsersIndexRoute =
  AppAuthSuperuserUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AppAuthSuperuserRoute,
  } as any)
const AppAuthResourcesGroupsIdRoute =
  AppAuthResourcesGroupsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppAuthResourcesGroupsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/reset-password': typeof AppResetPasswordRoute
  '/setup': typeof AppSetupRoute
  '/audit': typeof AppAuthAuditRoute
  '/dashboard': typeof AppAuthDashboardRoute
  '/docker': typeof AppAuthDockerRoute
  '/profile': typeof AppAuthProfileRoute
  '/services': typeof AppAuthServicesRoute
  '/space': typeof AppAuthSpaceRoute
  '/iac': typeof AppAuthSuperuserIacRoute
  '/logs': typeof AppAuthSuperuserLogsRoute
  '/settings': typeof AppAuthSuperuserSettingsRoute
  '/resources/certificates': typeof AppAuthResourcesCertificatesRoute
  '/resources/cloud-accounts': typeof AppAuthResourcesCloudAccountsRoute
  '/resources/databases': typeof AppAuthResourcesDatabasesRoute
  '/resources/env-groups': typeof AppAuthResourcesEnvGroupsRoute
  '/resources/groups': typeof AppAuthResourcesGroupsRouteWithChildren
  '/resources/integrations': typeof AppAuthResourcesIntegrationsRoute
  '/resources/scripts': typeof AppAuthResourcesScriptsRoute
  '/resources/secrets': typeof AppAuthResourcesSecretsRoute
  '/resources/servers': typeof AppAuthResourcesServersRoute
  '/resources/': typeof AppAuthResourcesIndexRoute
  '/store/': typeof AppAuthStoreIndexRoute
  '/resources/groups/$id': typeof AppAuthResourcesGroupsIdRoute
  '/users/': typeof AppAuthSuperuserUsersIndexRoute
  '/resources/groups/': typeof AppAuthResourcesGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/reset-password': typeof AppResetPasswordRoute
  '/setup': typeof AppSetupRoute
  '/audit': typeof AppAuthAuditRoute
  '/dashboard': typeof AppAuthDashboardRoute
  '/docker': typeof AppAuthDockerRoute
  '/profile': typeof AppAuthProfileRoute
  '/services': typeof AppAuthServicesRoute
  '/space': typeof AppAuthSpaceRoute
  '/iac': typeof AppAuthSuperuserIacRoute
  '/logs': typeof AppAuthSuperuserLogsRoute
  '/settings': typeof AppAuthSuperuserSettingsRoute
  '/resources/certificates': typeof AppAuthResourcesCertificatesRoute
  '/resources/cloud-accounts': typeof AppAuthResourcesCloudAccountsRoute
  '/resources/databases': typeof AppAuthResourcesDatabasesRoute
  '/resources/env-groups': typeof AppAuthResourcesEnvGroupsRoute
  '/resources/integrations': typeof AppAuthResourcesIntegrationsRoute
  '/resources/scripts': typeof AppAuthResourcesScriptsRoute
  '/resources/secrets': typeof AppAuthResourcesSecretsRoute
  '/resources/servers': typeof AppAuthResourcesServersRoute
  '/resources': typeof AppAuthResourcesIndexRoute
  '/store': typeof AppAuthStoreIndexRoute
  '/resources/groups/$id': typeof AppAuthResourcesGroupsIdRoute
  '/users': typeof AppAuthSuperuserUsersIndexRoute
  '/resources/groups': typeof AppAuthResourcesGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/forgot-password': typeof AppForgotPasswordRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/reset-password': typeof AppResetPasswordRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/_auth/_superuser': typeof AppAuthSuperuserRouteWithChildren
  '/_app/_auth/audit': typeof AppAuthAuditRoute
  '/_app/_auth/dashboard': typeof AppAuthDashboardRoute
  '/_app/_auth/docker': typeof AppAuthDockerRoute
  '/_app/_auth/profile': typeof AppAuthProfileRoute
  '/_app/_auth/services': typeof AppAuthServicesRoute
  '/_app/_auth/space': typeof AppAuthSpaceRoute
  '/_app/_auth/_superuser/iac': typeof AppAuthSuperuserIacRoute
  '/_app/_auth/_superuser/logs': typeof AppAuthSuperuserLogsRoute
  '/_app/_auth/_superuser/settings': typeof AppAuthSuperuserSettingsRoute
  '/_app/_auth/resources/certificates': typeof AppAuthResourcesCertificatesRoute
  '/_app/_auth/resources/cloud-accounts': typeof AppAuthResourcesCloudAccountsRoute
  '/_app/_auth/resources/databases': typeof AppAuthResourcesDatabasesRoute
  '/_app/_auth/resources/env-groups': typeof AppAuthResourcesEnvGroupsRoute
  '/_app/_auth/resources/groups': typeof AppAuthResourcesGroupsRouteWithChildren
  '/_app/_auth/resources/integrations': typeof AppAuthResourcesIntegrationsRoute
  '/_app/_auth/resources/scripts': typeof AppAuthResourcesScriptsRoute
  '/_app/_auth/resources/secrets': typeof AppAuthResourcesSecretsRoute
  '/_app/_auth/resources/servers': typeof AppAuthResourcesServersRoute
  '/_app/_auth/resources/': typeof AppAuthResourcesIndexRoute
  '/_app/_auth/store/': typeof AppAuthStoreIndexRoute
  '/_app/_auth/resources/groups/$id': typeof AppAuthResourcesGroupsIdRoute
  '/_app/_auth/_superuser/users/': typeof AppAuthSuperuserUsersIndexRoute
  '/_app/_auth/resources/groups/': typeof AppAuthResourcesGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/audit'
    | '/dashboard'
    | '/docker'
    | '/profile'
    | '/services'
    | '/space'
    | '/iac'
    | '/logs'
    | '/settings'
    | '/resources/certificates'
    | '/resources/cloud-accounts'
    | '/resources/databases'
    | '/resources/env-groups'
    | '/resources/groups'
    | '/resources/integrations'
    | '/resources/scripts'
    | '/resources/secrets'
    | '/resources/servers'
    | '/resources/'
    | '/store/'
    | '/resources/groups/$id'
    | '/users/'
    | '/resources/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/audit'
    | '/dashboard'
    | '/docker'
    | '/profile'
    | '/services'
    | '/space'
    | '/iac'
    | '/logs'
    | '/settings'
    | '/resources/certificates'
    | '/resources/cloud-accounts'
    | '/resources/databases'
    | '/resources/env-groups'
    | '/resources/integrations'
    | '/resources/scripts'
    | '/resources/secrets'
    | '/resources/servers'
    | '/resources'
    | '/store'
    | '/resources/groups/$id'
    | '/users'
    | '/resources/groups'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_auth'
    | '/_app/forgot-password'
    | '/_app/login'
    | '/_app/register'
    | '/_app/reset-password'
    | '/_app/setup'
    | '/_app/_auth/_superuser'
    | '/_app/_auth/audit'
    | '/_app/_auth/dashboard'
    | '/_app/_auth/docker'
    | '/_app/_auth/profile'
    | '/_app/_auth/services'
    | '/_app/_auth/space'
    | '/_app/_auth/_superuser/iac'
    | '/_app/_auth/_superuser/logs'
    | '/_app/_auth/_superuser/settings'
    | '/_app/_auth/resources/certificates'
    | '/_app/_auth/resources/cloud-accounts'
    | '/_app/_auth/resources/databases'
    | '/_app/_auth/resources/env-groups'
    | '/_app/_auth/resources/groups'
    | '/_app/_auth/resources/integrations'
    | '/_app/_auth/resources/scripts'
    | '/_app/_auth/resources/secrets'
    | '/_app/_auth/resources/servers'
    | '/_app/_auth/resources/'
    | '/_app/_auth/store/'
    | '/_app/_auth/resources/groups/$id'
    | '/_app/_auth/_superuser/users/'
    | '/_app/_auth/resources/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reset-password': {
      id: '/_app/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AppResetPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forgot-password': {
      id: '/_app/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth/space': {
      id: '/_app/_auth/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof AppAuthSpaceRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/services': {
      id: '/_app/_auth/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppAuthServicesRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/profile': {
      id: '/_app/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppAuthProfileRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/docker': {
      id: '/_app/_auth/docker'
      path: '/docker'
      fullPath: '/docker'
      preLoaderRoute: typeof AppAuthDockerRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard': {
      id: '/_app/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/audit': {
      id: '/_app/_auth/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuthAuditRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/_superuser': {
      id: '/_app/_auth/_superuser'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthSuperuserRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/store/': {
      id: '/_app/_auth/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof AppAuthStoreIndexRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/': {
      id: '/_app/_auth/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof AppAuthResourcesIndexRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/servers': {
      id: '/_app/_auth/resources/servers'
      path: '/resources/servers'
      fullPath: '/resources/servers'
      preLoaderRoute: typeof AppAuthResourcesServersRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/secrets': {
      id: '/_app/_auth/resources/secrets'
      path: '/resources/secrets'
      fullPath: '/resources/secrets'
      preLoaderRoute: typeof AppAuthResourcesSecretsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/scripts': {
      id: '/_app/_auth/resources/scripts'
      path: '/resources/scripts'
      fullPath: '/resources/scripts'
      preLoaderRoute: typeof AppAuthResourcesScriptsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/integrations': {
      id: '/_app/_auth/resources/integrations'
      path: '/resources/integrations'
      fullPath: '/resources/integrations'
      preLoaderRoute: typeof AppAuthResourcesIntegrationsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/groups': {
      id: '/_app/_auth/resources/groups'
      path: '/resources/groups'
      fullPath: '/resources/groups'
      preLoaderRoute: typeof AppAuthResourcesGroupsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/env-groups': {
      id: '/_app/_auth/resources/env-groups'
      path: '/resources/env-groups'
      fullPath: '/resources/env-groups'
      preLoaderRoute: typeof AppAuthResourcesEnvGroupsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/databases': {
      id: '/_app/_auth/resources/databases'
      path: '/resources/databases'
      fullPath: '/resources/databases'
      preLoaderRoute: typeof AppAuthResourcesDatabasesRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/cloud-accounts': {
      id: '/_app/_auth/resources/cloud-accounts'
      path: '/resources/cloud-accounts'
      fullPath: '/resources/cloud-accounts'
      preLoaderRoute: typeof AppAuthResourcesCloudAccountsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/certificates': {
      id: '/_app/_auth/resources/certificates'
      path: '/resources/certificates'
      fullPath: '/resources/certificates'
      preLoaderRoute: typeof AppAuthResourcesCertificatesRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/_superuser/settings': {
      id: '/_app/_auth/_superuser/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppAuthSuperuserSettingsRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/_superuser/logs': {
      id: '/_app/_auth/_superuser/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppAuthSuperuserLogsRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/_superuser/iac': {
      id: '/_app/_auth/_superuser/iac'
      path: '/iac'
      fullPath: '/iac'
      preLoaderRoute: typeof AppAuthSuperuserIacRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/resources/groups/': {
      id: '/_app/_auth/resources/groups/'
      path: '/'
      fullPath: '/resources/groups/'
      preLoaderRoute: typeof AppAuthResourcesGroupsIndexRouteImport
      parentRoute: typeof AppAuthResourcesGroupsRoute
    }
    '/_app/_auth/_superuser/users/': {
      id: '/_app/_auth/_superuser/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppAuthSuperuserUsersIndexRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/resources/groups/$id': {
      id: '/_app/_auth/resources/groups/$id'
      path: '/$id'
      fullPath: '/resources/groups/$id'
      preLoaderRoute: typeof AppAuthResourcesGroupsIdRouteImport
      parentRoute: typeof AppAuthResourcesGroupsRoute
    }
  }
}

interface AppAuthSuperuserRouteChildren {
  AppAuthSuperuserIacRoute: typeof AppAuthSuperuserIacRoute
  AppAuthSuperuserLogsRoute: typeof AppAuthSuperuserLogsRoute
  AppAuthSuperuserSettingsRoute: typeof AppAuthSuperuserSettingsRoute
  AppAuthSuperuserUsersIndexRoute: typeof AppAuthSuperuserUsersIndexRoute
}

const AppAuthSuperuserRouteChildren: AppAuthSuperuserRouteChildren = {
  AppAuthSuperuserIacRoute: AppAuthSuperuserIacRoute,
  AppAuthSuperuserLogsRoute: AppAuthSuperuserLogsRoute,
  AppAuthSuperuserSettingsRoute: AppAuthSuperuserSettingsRoute,
  AppAuthSuperuserUsersIndexRoute: AppAuthSuperuserUsersIndexRoute,
}

const AppAuthSuperuserRouteWithChildren =
  AppAuthSuperuserRoute._addFileChildren(AppAuthSuperuserRouteChildren)

interface AppAuthResourcesGroupsRouteChildren {
  AppAuthResourcesGroupsIdRoute: typeof AppAuthResourcesGroupsIdRoute
  AppAuthResourcesGroupsIndexRoute: typeof AppAuthResourcesGroupsIndexRoute
}

const AppAuthResourcesGroupsRouteChildren: AppAuthResourcesGroupsRouteChildren =
  {
    AppAuthResourcesGroupsIdRoute: AppAuthResourcesGroupsIdRoute,
    AppAuthResourcesGroupsIndexRoute: AppAuthResourcesGroupsIndexRoute,
  }

const AppAuthResourcesGroupsRouteWithChildren =
  AppAuthResourcesGroupsRoute._addFileChildren(
    AppAuthResourcesGroupsRouteChildren,
  )

interface AppAuthRouteChildren {
  AppAuthSuperuserRoute: typeof AppAuthSuperuserRouteWithChildren
  AppAuthAuditRoute: typeof AppAuthAuditRoute
  AppAuthDashboardRoute: typeof AppAuthDashboardRoute
  AppAuthDockerRoute: typeof AppAuthDockerRoute
  AppAuthProfileRoute: typeof AppAuthProfileRoute
  AppAuthServicesRoute: typeof AppAuthServicesRoute
  AppAuthSpaceRoute: typeof AppAuthSpaceRoute
  AppAuthResourcesCertificatesRoute: typeof AppAuthResourcesCertificatesRoute
  AppAuthResourcesCloudAccountsRoute: typeof AppAuthResourcesCloudAccountsRoute
  AppAuthResourcesDatabasesRoute: typeof AppAuthResourcesDatabasesRoute
  AppAuthResourcesEnvGroupsRoute: typeof AppAuthResourcesEnvGroupsRoute
  AppAuthResourcesGroupsRoute: typeof AppAuthResourcesGroupsRouteWithChildren
  AppAuthResourcesIntegrationsRoute: typeof AppAuthResourcesIntegrationsRoute
  AppAuthResourcesScriptsRoute: typeof AppAuthResourcesScriptsRoute
  AppAuthResourcesSecretsRoute: typeof AppAuthResourcesSecretsRoute
  AppAuthResourcesServersRoute: typeof AppAuthResourcesServersRoute
  AppAuthResourcesIndexRoute: typeof AppAuthResourcesIndexRoute
  AppAuthStoreIndexRoute: typeof AppAuthStoreIndexRoute
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthSuperuserRoute: AppAuthSuperuserRouteWithChildren,
  AppAuthAuditRoute: AppAuthAuditRoute,
  AppAuthDashboardRoute: AppAuthDashboardRoute,
  AppAuthDockerRoute: AppAuthDockerRoute,
  AppAuthProfileRoute: AppAuthProfileRoute,
  AppAuthServicesRoute: AppAuthServicesRoute,
  AppAuthSpaceRoute: AppAuthSpaceRoute,
  AppAuthResourcesCertificatesRoute: AppAuthResourcesCertificatesRoute,
  AppAuthResourcesCloudAccountsRoute: AppAuthResourcesCloudAccountsRoute,
  AppAuthResourcesDatabasesRoute: AppAuthResourcesDatabasesRoute,
  AppAuthResourcesEnvGroupsRoute: AppAuthResourcesEnvGroupsRoute,
  AppAuthResourcesGroupsRoute: AppAuthResourcesGroupsRouteWithChildren,
  AppAuthResourcesIntegrationsRoute: AppAuthResourcesIntegrationsRoute,
  AppAuthResourcesScriptsRoute: AppAuthResourcesScriptsRoute,
  AppAuthResourcesSecretsRoute: AppAuthResourcesSecretsRoute,
  AppAuthResourcesServersRoute: AppAuthResourcesServersRoute,
  AppAuthResourcesIndexRoute: AppAuthResourcesIndexRoute,
  AppAuthStoreIndexRoute: AppAuthStoreIndexRoute,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppResetPasswordRoute: typeof AppResetPasswordRoute
  AppSetupRoute: typeof AppSetupRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppResetPasswordRoute: AppResetPasswordRoute,
  AppSetupRoute: AppSetupRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
