/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSetupRouteImport } from './routes/_app/setup'
import { Route as AppResetPasswordRouteImport } from './routes/_app/reset-password'
import { Route as AppRegisterRouteImport } from './routes/_app/register'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppForgotPasswordRouteImport } from './routes/_app/forgot-password'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppAuthServicesRouteImport } from './routes/_app/_auth/services'
import { Route as AppAuthDockerRouteImport } from './routes/_app/_auth/docker'
import { Route as AppAuthDashboardRouteImport } from './routes/_app/_auth/dashboard'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppResetPasswordRoute = AppResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthServicesRoute = AppAuthServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDockerRoute = AppAuthDockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardRoute = AppAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/reset-password': typeof AppResetPasswordRoute
  '/setup': typeof AppSetupRoute
  '/dashboard': typeof AppAuthDashboardRoute
  '/docker': typeof AppAuthDockerRoute
  '/services': typeof AppAuthServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/reset-password': typeof AppResetPasswordRoute
  '/setup': typeof AppSetupRoute
  '/dashboard': typeof AppAuthDashboardRoute
  '/docker': typeof AppAuthDockerRoute
  '/services': typeof AppAuthServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/forgot-password': typeof AppForgotPasswordRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/reset-password': typeof AppResetPasswordRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/_auth/dashboard': typeof AppAuthDashboardRoute
  '/_app/_auth/docker': typeof AppAuthDockerRoute
  '/_app/_auth/services': typeof AppAuthServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/dashboard'
    | '/docker'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/dashboard'
    | '/docker'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_auth'
    | '/_app/forgot-password'
    | '/_app/login'
    | '/_app/register'
    | '/_app/reset-password'
    | '/_app/setup'
    | '/_app/_auth/dashboard'
    | '/_app/_auth/docker'
    | '/_app/_auth/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reset-password': {
      id: '/_app/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AppResetPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forgot-password': {
      id: '/_app/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth/services': {
      id: '/_app/_auth/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppAuthServicesRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/docker': {
      id: '/_app/_auth/docker'
      path: '/docker'
      fullPath: '/docker'
      preLoaderRoute: typeof AppAuthDockerRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard': {
      id: '/_app/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardRouteImport
      parentRoute: typeof AppAuthRoute
    }
  }
}

interface AppAuthRouteChildren {
  AppAuthDashboardRoute: typeof AppAuthDashboardRoute
  AppAuthDockerRoute: typeof AppAuthDockerRoute
  AppAuthServicesRoute: typeof AppAuthServicesRoute
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthDashboardRoute: AppAuthDashboardRoute,
  AppAuthDockerRoute: AppAuthDockerRoute,
  AppAuthServicesRoute: AppAuthServicesRoute,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppResetPasswordRoute: typeof AppResetPasswordRoute
  AppSetupRoute: typeof AppSetupRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppResetPasswordRoute: AppResetPasswordRoute,
  AppSetupRoute: AppSetupRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
