package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type openAPIDoc struct {
	OpenAPI      string                    `yaml:"openapi,omitempty"`
	Info         map[string]any            `yaml:"info,omitempty"`
	ExternalDocs map[string]any            `yaml:"externalDocs,omitempty"`
	Servers      []map[string]any          `yaml:"servers,omitempty"`
	Tags         []map[string]any          `yaml:"tags,omitempty"`
	Components   map[string]any            `yaml:"components,omitempty"`
	Paths        map[string]map[string]any `yaml:"paths,omitempty"`
}

type groupMatrix struct {
	Groups []groupNameEntry `yaml:"groups"`
}

type groupNameEntry struct {
	Group string `yaml:"group"`
}

func runMerge() error {
	_, thisFile, _, _ := runtime.Caller(0)
	root := filepath.Join(filepath.Dir(thisFile), "../..")
	openapiDir := filepath.Join(root, "docs/openapi")
	extPath := filepath.Join(openapiDir, "ext-api.yaml")
	nativePath := filepath.Join(openapiDir, "native-api.yaml")
	groupMatrixPath := filepath.Join(openapiDir, "group-matrix.yaml")
	outPath := filepath.Join(openapiDir, "api.yaml")

	extDoc, err := readDoc(extPath)
	if err != nil {
		return fmt.Errorf("cannot read ext spec: %w", err)
	}
	nativeDoc, err := readDoc(nativePath)
	if err != nil {
		return fmt.Errorf("cannot read native spec: %w", err)
	}

	groupOrder, err := readGroupOrder(groupMatrixPath)
	if err != nil {
		return fmt.Errorf("cannot read group matrix: %w", err)
	}

	merged := openAPIDoc{
		OpenAPI:      firstNonEmpty(extDoc.OpenAPI, nativeDoc.OpenAPI, "3.0.3"),
		Info:         mergeInfo(extDoc.Info, nativeDoc.Info),
		ExternalDocs: map[string]any{},
		Servers:      nil,
		Tags:         stripTagExternalDocs(mergeTags(extDoc.Tags, nativeDoc.Tags, groupOrder)),
		Components:   mergeMaps(nativeDoc.Components, extDoc.Components),
		Paths:        mergePaths(nativeDoc.Paths, extDoc.Paths),
	}

	body, err := yaml.Marshal(merged)
	if err != nil {
		return fmt.Errorf("cannot marshal merged spec: %w", err)
	}

		header := "# This file is generated by backend/cmd/merge-openapi/main.go\n" +
			"# Source files: ext-api.yaml (generated custom-route spec) + native-api.yaml (manual)\n" +
		"# Do not edit manually. Run: make openapi-sync\n\n"

	if err := os.WriteFile(outPath, append([]byte(header), body...), 0644); err != nil {
		return fmt.Errorf("cannot write merged spec: %w", err)
	}

	fmt.Printf("Merged OpenAPI spec written to %s\n", outPath)
	return nil
}

func readDoc(path string) (openAPIDoc, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return openAPIDoc{}, err
	}
	var doc openAPIDoc
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return openAPIDoc{}, err
	}
	if doc.Paths == nil {
		doc.Paths = map[string]map[string]any{}
	}
	if doc.Components == nil {
		doc.Components = map[string]any{}
	}
	if doc.Info == nil {
		doc.Info = map[string]any{}
	}
	return doc, nil
}

func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if v != "" {
			return v
		}
	}
	return ""
}

func mergeInfo(extInfo, nativeInfo map[string]any) map[string]any {
	out := mergeMaps(nativeInfo, extInfo)
	if _, ok := out["title"]; !ok {
		out["title"] = "AppOS API"
	}
	if _, ok := out["description"]; !ok {
		out["description"] = "Merged OpenAPI specification for AppOS (generated custom routes + native APIs)."
	}
	return out
}

func firstMap(a, b map[string]any) map[string]any {
	if len(a) > 0 {
		return cloneMap(a)
	}
	return cloneMap(b)
}

func firstServers(a, b []map[string]any) []map[string]any {
	if len(a) > 0 {
		return cloneServers(a)
	}
	return cloneServers(b)
}

func readGroupOrder(path string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var gm groupMatrix
	if err := yaml.Unmarshal(data, &gm); err != nil {
		return nil, err
	}
	seen := map[string]struct{}{}
	out := make([]string, 0, len(gm.Groups))
	for _, group := range gm.Groups {
		name := strings.TrimSpace(group.Group)
		if name == "" {
			continue
		}
		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}
		out = append(out, name)
	}
	return out, nil
}

func mergeTags(extTags, nativeTags []map[string]any, groupOrder []string) []map[string]any {
	byName := map[string]map[string]any{}
	addTag := func(tag map[string]any) {
		name, _ := tag["name"].(string)
		name = strings.TrimSpace(name)
		if name == "" {
			return
		}
		if _, exists := byName[name]; exists {
			return
		}
		byName[name] = cloneMap(tag)
	}
	for _, tag := range extTags {
		addTag(tag)
	}
	for _, tag := range nativeTags {
		addTag(tag)
	}

	out := make([]map[string]any, 0, len(byName))
	used := map[string]struct{}{}
	for _, name := range groupOrder {
		if tag, ok := byName[name]; ok {
			out = append(out, tag)
			used[name] = struct{}{}
		}
	}

	rest := make([]string, 0)
	for name := range byName {
		if _, ok := used[name]; ok {
			continue
		}
		rest = append(rest, name)
	}
	sort.Strings(rest)
	for _, name := range rest {
		out = append(out, byName[name])
	}

	return out
}

func stripTagExternalDocs(tags []map[string]any) []map[string]any {
	for _, tag := range tags {
		delete(tag, "externalDocs")
	}
	return tags
}

func mergePaths(nativePaths, extPaths map[string]map[string]any) map[string]map[string]any {
	out := map[string]map[string]any{}
	for p, m := range nativePaths {
		out[p] = cloneMap(m)
	}
	for p, m := range extPaths {
		out[p] = cloneMap(m)
	}
	return out
}

func mergeMaps(base, override map[string]any) map[string]any {
	out := cloneMap(base)
	for k, v := range override {
		if vm, vok := v.(map[string]any); vok {
			if bm, bok := out[k].(map[string]any); bok {
				out[k] = mergeMaps(bm, vm)
				continue
			}
		}
		out[k] = v
	}
	return out
}

func cloneMap(in map[string]any) map[string]any {
	if in == nil {
		return map[string]any{}
	}
	out := make(map[string]any, len(in))
	for k, v := range in {
		if vm, ok := v.(map[string]any); ok {
			out[k] = cloneMap(vm)
			continue
		}
		out[k] = v
	}
	return out
}

func cloneServers(in []map[string]any) []map[string]any {
	out := make([]map[string]any, 0, len(in))
	for _, srv := range in {
		out = append(out, cloneMap(srv))
	}
	return out
}
