/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSetupRouteImport } from './routes/_app/setup'
import { Route as AppResetPasswordRouteImport } from './routes/_app/reset-password'
import { Route as AppRegisterRouteImport } from './routes/_app/register'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppForgotPasswordRouteImport } from './routes/_app/forgot-password'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as ShareTopicTokenRouteImport } from './routes/share/topic.$token'
import { Route as AppAuthTopicsRouteImport } from './routes/_app/_auth/topics'
import { Route as AppAuthSpaceRouteImport } from './routes/_app/_auth/space'
import { Route as AppAuthSharedEnvsRouteImport } from './routes/_app/_auth/shared-envs'
import { Route as AppAuthSecretsRouteImport } from './routes/_app/_auth/secrets'
import { Route as AppAuthProfileRouteImport } from './routes/_app/_auth/profile'
import { Route as AppAuthOverviewRouteImport } from './routes/_app/_auth/overview'
import { Route as AppAuthGroupsRouteImport } from './routes/_app/_auth/groups'
import { Route as AppAuthDockerRouteImport } from './routes/_app/_auth/docker'
import { Route as AppAuthDeployRouteImport } from './routes/_app/_auth/deploy'
import { Route as AppAuthComponentsRouteImport } from './routes/_app/_auth/components'
import { Route as AppAuthCertificatesRouteImport } from './routes/_app/_auth/certificates'
import { Route as AppAuthAuditRouteImport } from './routes/_app/_auth/audit'
import { Route as AppAuthAppsRouteImport } from './routes/_app/_auth/apps'
import { Route as AppAuthActionsRouteImport } from './routes/_app/_auth/actions'
import { Route as AppAuthSuperuserRouteImport } from './routes/_app/_auth/_superuser'
import { Route as AppAuthTopicsIndexRouteImport } from './routes/_app/_auth/topics.index'
import { Route as AppAuthStoreIndexRouteImport } from './routes/_app/_auth/store/index'
import { Route as AppAuthResourcesIndexRouteImport } from './routes/_app/_auth/resources/index'
import { Route as AppAuthGroupsIndexRouteImport } from './routes/_app/_auth/groups.index'
import { Route as AppAuthDeployIndexRouteImport } from './routes/_app/_auth/deploy.index'
import { Route as AppAuthTopicsIdRouteImport } from './routes/_app/_auth/topics.$id'
import { Route as AppAuthResourcesTunnelsRouteImport } from './routes/_app/_auth/resources/tunnels'
import { Route as AppAuthResourcesServiceInstancesRouteImport } from './routes/_app/_auth/resources/service-instances'
import { Route as AppAuthResourcesServersRouteImport } from './routes/_app/_auth/resources/servers'
import { Route as AppAuthResourcesScriptsRouteImport } from './routes/_app/_auth/resources/scripts'
import { Route as AppAuthResourcesPlatformAccountsRouteImport } from './routes/_app/_auth/resources/platform-accounts'
import { Route as AppAuthResourcesConnectorsRouteImport } from './routes/_app/_auth/resources/connectors'
import { Route as AppAuthResourcesAiProvidersRouteImport } from './routes/_app/_auth/resources/ai-providers'
import { Route as AppAuthGroupsIdRouteImport } from './routes/_app/_auth/groups.$id'
import { Route as AppAuthDeployCreateRouteImport } from './routes/_app/_auth/deploy.create'
import { Route as AppAuthAppsAppIdRouteImport } from './routes/_app/_auth/apps.$appId'
import { Route as AppAuthActionsActionIdRouteImport } from './routes/_app/_auth/actions.$actionId'
import { Route as AppAuthSuperuserTunnelsRouteImport } from './routes/_app/_auth/_superuser/tunnels'
import { Route as AppAuthSuperuserSystemTasksRouteImport } from './routes/_app/_auth/_superuser/system-tasks'
import { Route as AppAuthSuperuserStatusRouteImport } from './routes/_app/_auth/_superuser/status'
import { Route as AppAuthSuperuserSettingsRouteImport } from './routes/_app/_auth/_superuser/settings'
import { Route as AppAuthSuperuserLogsRouteImport } from './routes/_app/_auth/_superuser/logs'
import { Route as AppAuthSuperuserIacRouteImport } from './routes/_app/_auth/_superuser/iac'
import { Route as AppAuthSuperuserUsersIndexRouteImport } from './routes/_app/_auth/_superuser/users/index'
import { Route as AppAuthSuperuserTerminalIndexRouteImport } from './routes/_app/_auth/_superuser/terminal.index'
import { Route as AppAuthAdminCredentialsEnvVarsRouteImport } from './routes/_app/_auth/admin/credentials/env-vars'
import { Route as AppAuthSuperuserTerminalServerServerIdRouteImport } from './routes/_app/_auth/_superuser/terminal.server.$serverId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppResetPasswordRoute = AppResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const ShareTopicTokenRoute = ShareTopicTokenRouteImport.update({
  id: '/share/topic/$token',
  path: '/share/topic/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthTopicsRoute = AppAuthTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthSpaceRoute = AppAuthSpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthSharedEnvsRoute = AppAuthSharedEnvsRouteImport.update({
  id: '/shared-envs',
  path: '/shared-envs',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthSecretsRoute = AppAuthSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthProfileRoute = AppAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthOverviewRoute = AppAuthOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthGroupsRoute = AppAuthGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDockerRoute = AppAuthDockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDeployRoute = AppAuthDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthComponentsRoute = AppAuthComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthCertificatesRoute = AppAuthCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthAuditRoute = AppAuthAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthAppsRoute = AppAuthAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthActionsRoute = AppAuthActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthSuperuserRoute = AppAuthSuperuserRouteImport.update({
  id: '/_superuser',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthTopicsIndexRoute = AppAuthTopicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthTopicsRoute,
} as any)
const AppAuthStoreIndexRoute = AppAuthStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthResourcesIndexRoute = AppAuthResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthGroupsIndexRoute = AppAuthGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthGroupsRoute,
} as any)
const AppAuthDeployIndexRoute = AppAuthDeployIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthDeployRoute,
} as any)
const AppAuthTopicsIdRoute = AppAuthTopicsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAuthTopicsRoute,
} as any)
const AppAuthResourcesTunnelsRoute = AppAuthResourcesTunnelsRouteImport.update({
  id: '/resources/tunnels',
  path: '/resources/tunnels',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthResourcesServiceInstancesRoute =
  AppAuthResourcesServiceInstancesRouteImport.update({
    id: '/resources/service-instances',
    path: '/resources/service-instances',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthResourcesServersRoute = AppAuthResourcesServersRouteImport.update({
  id: '/resources/servers',
  path: '/resources/servers',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthResourcesScriptsRoute = AppAuthResourcesScriptsRouteImport.update({
  id: '/resources/scripts',
  path: '/resources/scripts',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthResourcesPlatformAccountsRoute =
  AppAuthResourcesPlatformAccountsRouteImport.update({
    id: '/resources/platform-accounts',
    path: '/resources/platform-accounts',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthResourcesConnectorsRoute =
  AppAuthResourcesConnectorsRouteImport.update({
    id: '/resources/connectors',
    path: '/resources/connectors',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthResourcesAiProvidersRoute =
  AppAuthResourcesAiProvidersRouteImport.update({
    id: '/resources/ai-providers',
    path: '/resources/ai-providers',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthGroupsIdRoute = AppAuthGroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAuthGroupsRoute,
} as any)
const AppAuthDeployCreateRoute = AppAuthDeployCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppAuthDeployRoute,
} as any)
const AppAuthAppsAppIdRoute = AppAuthAppsAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => AppAuthAppsRoute,
} as any)
const AppAuthActionsActionIdRoute = AppAuthActionsActionIdRouteImport.update({
  id: '/$actionId',
  path: '/$actionId',
  getParentRoute: () => AppAuthActionsRoute,
} as any)
const AppAuthSuperuserTunnelsRoute = AppAuthSuperuserTunnelsRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => AppAuthSuperuserRoute,
} as any)
const AppAuthSuperuserSystemTasksRoute =
  AppAuthSuperuserSystemTasksRouteImport.update({
    id: '/system-tasks',
    path: '/system-tasks',
    getParentRoute: () => AppAuthSuperuserRoute,
  } as any)
const AppAuthSuperuserStatusRoute = AppAuthSuperuserStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppAuthSuperuserRoute,
} as any)
const AppAuthSuperuserSettingsRoute =
  AppAuthSuperuserSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthSuperuserRoute,
  } as any)
const AppAuthSuperuserLogsRoute = AppAuthSuperuserLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAuthSuperuserRoute,
} as any)
const AppAuthSuperuserIacRoute = AppAuthSuperuserIacRouteImport.update({
  id: '/iac',
  path: '/iac',
  getParentRoute: () => AppAuthSuperuserRoute,
} as any)
const AppAuthSuperuserUsersIndexRoute =
  AppAuthSuperuserUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AppAuthSuperuserRoute,
  } as any)
const AppAuthSuperuserTerminalIndexRoute =
  AppAuthSuperuserTerminalIndexRouteImport.update({
    id: '/terminal/',
    path: '/terminal/',
    getParentRoute: () => AppAuthSuperuserRoute,
  } as any)
const AppAuthAdminCredentialsEnvVarsRoute =
  AppAuthAdminCredentialsEnvVarsRouteImport.update({
    id: '/admin/credentials/env-vars',
    path: '/admin/credentials/env-vars',
    getParentRoute: () => AppAuthRoute,
  } as any)
const AppAuthSuperuserTerminalServerServerIdRoute =
  AppAuthSuperuserTerminalServerServerIdRouteImport.update({
    id: '/terminal/server/$serverId',
    path: '/terminal/server/$serverId',
    getParentRoute: () => AppAuthSuperuserRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/reset-password': typeof AppResetPasswordRoute
  '/setup': typeof AppSetupRoute
  '/actions': typeof AppAuthActionsRouteWithChildren
  '/apps': typeof AppAuthAppsRouteWithChildren
  '/audit': typeof AppAuthAuditRoute
  '/certificates': typeof AppAuthCertificatesRoute
  '/components': typeof AppAuthComponentsRoute
  '/deploy': typeof AppAuthDeployRouteWithChildren
  '/docker': typeof AppAuthDockerRoute
  '/groups': typeof AppAuthGroupsRouteWithChildren
  '/overview': typeof AppAuthOverviewRoute
  '/profile': typeof AppAuthProfileRoute
  '/secrets': typeof AppAuthSecretsRoute
  '/shared-envs': typeof AppAuthSharedEnvsRoute
  '/space': typeof AppAuthSpaceRoute
  '/topics': typeof AppAuthTopicsRouteWithChildren
  '/share/topic/$token': typeof ShareTopicTokenRoute
  '/iac': typeof AppAuthSuperuserIacRoute
  '/logs': typeof AppAuthSuperuserLogsRoute
  '/settings': typeof AppAuthSuperuserSettingsRoute
  '/status': typeof AppAuthSuperuserStatusRoute
  '/system-tasks': typeof AppAuthSuperuserSystemTasksRoute
  '/tunnels': typeof AppAuthSuperuserTunnelsRoute
  '/actions/$actionId': typeof AppAuthActionsActionIdRoute
  '/apps/$appId': typeof AppAuthAppsAppIdRoute
  '/deploy/create': typeof AppAuthDeployCreateRoute
  '/groups/$id': typeof AppAuthGroupsIdRoute
  '/resources/ai-providers': typeof AppAuthResourcesAiProvidersRoute
  '/resources/connectors': typeof AppAuthResourcesConnectorsRoute
  '/resources/platform-accounts': typeof AppAuthResourcesPlatformAccountsRoute
  '/resources/scripts': typeof AppAuthResourcesScriptsRoute
  '/resources/servers': typeof AppAuthResourcesServersRoute
  '/resources/service-instances': typeof AppAuthResourcesServiceInstancesRoute
  '/resources/tunnels': typeof AppAuthResourcesTunnelsRoute
  '/topics/$id': typeof AppAuthTopicsIdRoute
  '/deploy/': typeof AppAuthDeployIndexRoute
  '/groups/': typeof AppAuthGroupsIndexRoute
  '/resources/': typeof AppAuthResourcesIndexRoute
  '/store/': typeof AppAuthStoreIndexRoute
  '/topics/': typeof AppAuthTopicsIndexRoute
  '/admin/credentials/env-vars': typeof AppAuthAdminCredentialsEnvVarsRoute
  '/terminal/': typeof AppAuthSuperuserTerminalIndexRoute
  '/users/': typeof AppAuthSuperuserUsersIndexRoute
  '/terminal/server/$serverId': typeof AppAuthSuperuserTerminalServerServerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/reset-password': typeof AppResetPasswordRoute
  '/setup': typeof AppSetupRoute
  '/actions': typeof AppAuthActionsRouteWithChildren
  '/apps': typeof AppAuthAppsRouteWithChildren
  '/audit': typeof AppAuthAuditRoute
  '/certificates': typeof AppAuthCertificatesRoute
  '/components': typeof AppAuthComponentsRoute
  '/docker': typeof AppAuthDockerRoute
  '/overview': typeof AppAuthOverviewRoute
  '/profile': typeof AppAuthProfileRoute
  '/secrets': typeof AppAuthSecretsRoute
  '/shared-envs': typeof AppAuthSharedEnvsRoute
  '/space': typeof AppAuthSpaceRoute
  '/share/topic/$token': typeof ShareTopicTokenRoute
  '/iac': typeof AppAuthSuperuserIacRoute
  '/logs': typeof AppAuthSuperuserLogsRoute
  '/settings': typeof AppAuthSuperuserSettingsRoute
  '/status': typeof AppAuthSuperuserStatusRoute
  '/system-tasks': typeof AppAuthSuperuserSystemTasksRoute
  '/tunnels': typeof AppAuthSuperuserTunnelsRoute
  '/actions/$actionId': typeof AppAuthActionsActionIdRoute
  '/apps/$appId': typeof AppAuthAppsAppIdRoute
  '/deploy/create': typeof AppAuthDeployCreateRoute
  '/groups/$id': typeof AppAuthGroupsIdRoute
  '/resources/ai-providers': typeof AppAuthResourcesAiProvidersRoute
  '/resources/connectors': typeof AppAuthResourcesConnectorsRoute
  '/resources/platform-accounts': typeof AppAuthResourcesPlatformAccountsRoute
  '/resources/scripts': typeof AppAuthResourcesScriptsRoute
  '/resources/servers': typeof AppAuthResourcesServersRoute
  '/resources/service-instances': typeof AppAuthResourcesServiceInstancesRoute
  '/resources/tunnels': typeof AppAuthResourcesTunnelsRoute
  '/topics/$id': typeof AppAuthTopicsIdRoute
  '/deploy': typeof AppAuthDeployIndexRoute
  '/groups': typeof AppAuthGroupsIndexRoute
  '/resources': typeof AppAuthResourcesIndexRoute
  '/store': typeof AppAuthStoreIndexRoute
  '/topics': typeof AppAuthTopicsIndexRoute
  '/admin/credentials/env-vars': typeof AppAuthAdminCredentialsEnvVarsRoute
  '/terminal': typeof AppAuthSuperuserTerminalIndexRoute
  '/users': typeof AppAuthSuperuserUsersIndexRoute
  '/terminal/server/$serverId': typeof AppAuthSuperuserTerminalServerServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/forgot-password': typeof AppForgotPasswordRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/reset-password': typeof AppResetPasswordRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/_auth/_superuser': typeof AppAuthSuperuserRouteWithChildren
  '/_app/_auth/actions': typeof AppAuthActionsRouteWithChildren
  '/_app/_auth/apps': typeof AppAuthAppsRouteWithChildren
  '/_app/_auth/audit': typeof AppAuthAuditRoute
  '/_app/_auth/certificates': typeof AppAuthCertificatesRoute
  '/_app/_auth/components': typeof AppAuthComponentsRoute
  '/_app/_auth/deploy': typeof AppAuthDeployRouteWithChildren
  '/_app/_auth/docker': typeof AppAuthDockerRoute
  '/_app/_auth/groups': typeof AppAuthGroupsRouteWithChildren
  '/_app/_auth/overview': typeof AppAuthOverviewRoute
  '/_app/_auth/profile': typeof AppAuthProfileRoute
  '/_app/_auth/secrets': typeof AppAuthSecretsRoute
  '/_app/_auth/shared-envs': typeof AppAuthSharedEnvsRoute
  '/_app/_auth/space': typeof AppAuthSpaceRoute
  '/_app/_auth/topics': typeof AppAuthTopicsRouteWithChildren
  '/share/topic/$token': typeof ShareTopicTokenRoute
  '/_app/_auth/_superuser/iac': typeof AppAuthSuperuserIacRoute
  '/_app/_auth/_superuser/logs': typeof AppAuthSuperuserLogsRoute
  '/_app/_auth/_superuser/settings': typeof AppAuthSuperuserSettingsRoute
  '/_app/_auth/_superuser/status': typeof AppAuthSuperuserStatusRoute
  '/_app/_auth/_superuser/system-tasks': typeof AppAuthSuperuserSystemTasksRoute
  '/_app/_auth/_superuser/tunnels': typeof AppAuthSuperuserTunnelsRoute
  '/_app/_auth/actions/$actionId': typeof AppAuthActionsActionIdRoute
  '/_app/_auth/apps/$appId': typeof AppAuthAppsAppIdRoute
  '/_app/_auth/deploy/create': typeof AppAuthDeployCreateRoute
  '/_app/_auth/groups/$id': typeof AppAuthGroupsIdRoute
  '/_app/_auth/resources/ai-providers': typeof AppAuthResourcesAiProvidersRoute
  '/_app/_auth/resources/connectors': typeof AppAuthResourcesConnectorsRoute
  '/_app/_auth/resources/platform-accounts': typeof AppAuthResourcesPlatformAccountsRoute
  '/_app/_auth/resources/scripts': typeof AppAuthResourcesScriptsRoute
  '/_app/_auth/resources/servers': typeof AppAuthResourcesServersRoute
  '/_app/_auth/resources/service-instances': typeof AppAuthResourcesServiceInstancesRoute
  '/_app/_auth/resources/tunnels': typeof AppAuthResourcesTunnelsRoute
  '/_app/_auth/topics/$id': typeof AppAuthTopicsIdRoute
  '/_app/_auth/deploy/': typeof AppAuthDeployIndexRoute
  '/_app/_auth/groups/': typeof AppAuthGroupsIndexRoute
  '/_app/_auth/resources/': typeof AppAuthResourcesIndexRoute
  '/_app/_auth/store/': typeof AppAuthStoreIndexRoute
  '/_app/_auth/topics/': typeof AppAuthTopicsIndexRoute
  '/_app/_auth/admin/credentials/env-vars': typeof AppAuthAdminCredentialsEnvVarsRoute
  '/_app/_auth/_superuser/terminal/': typeof AppAuthSuperuserTerminalIndexRoute
  '/_app/_auth/_superuser/users/': typeof AppAuthSuperuserUsersIndexRoute
  '/_app/_auth/_superuser/terminal/server/$serverId': typeof AppAuthSuperuserTerminalServerServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/actions'
    | '/apps'
    | '/audit'
    | '/certificates'
    | '/components'
    | '/deploy'
    | '/docker'
    | '/groups'
    | '/overview'
    | '/profile'
    | '/secrets'
    | '/shared-envs'
    | '/space'
    | '/topics'
    | '/share/topic/$token'
    | '/iac'
    | '/logs'
    | '/settings'
    | '/status'
    | '/system-tasks'
    | '/tunnels'
    | '/actions/$actionId'
    | '/apps/$appId'
    | '/deploy/create'
    | '/groups/$id'
    | '/resources/ai-providers'
    | '/resources/connectors'
    | '/resources/platform-accounts'
    | '/resources/scripts'
    | '/resources/servers'
    | '/resources/service-instances'
    | '/resources/tunnels'
    | '/topics/$id'
    | '/deploy/'
    | '/groups/'
    | '/resources/'
    | '/store/'
    | '/topics/'
    | '/admin/credentials/env-vars'
    | '/terminal/'
    | '/users/'
    | '/terminal/server/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/actions'
    | '/apps'
    | '/audit'
    | '/certificates'
    | '/components'
    | '/docker'
    | '/overview'
    | '/profile'
    | '/secrets'
    | '/shared-envs'
    | '/space'
    | '/share/topic/$token'
    | '/iac'
    | '/logs'
    | '/settings'
    | '/status'
    | '/system-tasks'
    | '/tunnels'
    | '/actions/$actionId'
    | '/apps/$appId'
    | '/deploy/create'
    | '/groups/$id'
    | '/resources/ai-providers'
    | '/resources/connectors'
    | '/resources/platform-accounts'
    | '/resources/scripts'
    | '/resources/servers'
    | '/resources/service-instances'
    | '/resources/tunnels'
    | '/topics/$id'
    | '/deploy'
    | '/groups'
    | '/resources'
    | '/store'
    | '/topics'
    | '/admin/credentials/env-vars'
    | '/terminal'
    | '/users'
    | '/terminal/server/$serverId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_auth'
    | '/_app/forgot-password'
    | '/_app/login'
    | '/_app/register'
    | '/_app/reset-password'
    | '/_app/setup'
    | '/_app/_auth/_superuser'
    | '/_app/_auth/actions'
    | '/_app/_auth/apps'
    | '/_app/_auth/audit'
    | '/_app/_auth/certificates'
    | '/_app/_auth/components'
    | '/_app/_auth/deploy'
    | '/_app/_auth/docker'
    | '/_app/_auth/groups'
    | '/_app/_auth/overview'
    | '/_app/_auth/profile'
    | '/_app/_auth/secrets'
    | '/_app/_auth/shared-envs'
    | '/_app/_auth/space'
    | '/_app/_auth/topics'
    | '/share/topic/$token'
    | '/_app/_auth/_superuser/iac'
    | '/_app/_auth/_superuser/logs'
    | '/_app/_auth/_superuser/settings'
    | '/_app/_auth/_superuser/status'
    | '/_app/_auth/_superuser/system-tasks'
    | '/_app/_auth/_superuser/tunnels'
    | '/_app/_auth/actions/$actionId'
    | '/_app/_auth/apps/$appId'
    | '/_app/_auth/deploy/create'
    | '/_app/_auth/groups/$id'
    | '/_app/_auth/resources/ai-providers'
    | '/_app/_auth/resources/connectors'
    | '/_app/_auth/resources/platform-accounts'
    | '/_app/_auth/resources/scripts'
    | '/_app/_auth/resources/servers'
    | '/_app/_auth/resources/service-instances'
    | '/_app/_auth/resources/tunnels'
    | '/_app/_auth/topics/$id'
    | '/_app/_auth/deploy/'
    | '/_app/_auth/groups/'
    | '/_app/_auth/resources/'
    | '/_app/_auth/store/'
    | '/_app/_auth/topics/'
    | '/_app/_auth/admin/credentials/env-vars'
    | '/_app/_auth/_superuser/terminal/'
    | '/_app/_auth/_superuser/users/'
    | '/_app/_auth/_superuser/terminal/server/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ShareTopicTokenRoute: typeof ShareTopicTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reset-password': {
      id: '/_app/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AppResetPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forgot-password': {
      id: '/_app/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/topic/$token': {
      id: '/share/topic/$token'
      path: '/share/topic/$token'
      fullPath: '/share/topic/$token'
      preLoaderRoute: typeof ShareTopicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_auth/topics': {
      id: '/_app/_auth/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof AppAuthTopicsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/space': {
      id: '/_app/_auth/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof AppAuthSpaceRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/shared-envs': {
      id: '/_app/_auth/shared-envs'
      path: '/shared-envs'
      fullPath: '/shared-envs'
      preLoaderRoute: typeof AppAuthSharedEnvsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/secrets': {
      id: '/_app/_auth/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof AppAuthSecretsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/profile': {
      id: '/_app/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppAuthProfileRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/overview': {
      id: '/_app/_auth/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppAuthOverviewRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/groups': {
      id: '/_app/_auth/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppAuthGroupsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/docker': {
      id: '/_app/_auth/docker'
      path: '/docker'
      fullPath: '/docker'
      preLoaderRoute: typeof AppAuthDockerRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/deploy': {
      id: '/_app/_auth/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof AppAuthDeployRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/components': {
      id: '/_app/_auth/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof AppAuthComponentsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/certificates': {
      id: '/_app/_auth/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AppAuthCertificatesRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/audit': {
      id: '/_app/_auth/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuthAuditRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/apps': {
      id: '/_app/_auth/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppAuthAppsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/actions': {
      id: '/_app/_auth/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AppAuthActionsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/_superuser': {
      id: '/_app/_auth/_superuser'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthSuperuserRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/topics/': {
      id: '/_app/_auth/topics/'
      path: '/'
      fullPath: '/topics/'
      preLoaderRoute: typeof AppAuthTopicsIndexRouteImport
      parentRoute: typeof AppAuthTopicsRoute
    }
    '/_app/_auth/store/': {
      id: '/_app/_auth/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof AppAuthStoreIndexRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/': {
      id: '/_app/_auth/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof AppAuthResourcesIndexRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/groups/': {
      id: '/_app/_auth/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppAuthGroupsIndexRouteImport
      parentRoute: typeof AppAuthGroupsRoute
    }
    '/_app/_auth/deploy/': {
      id: '/_app/_auth/deploy/'
      path: '/'
      fullPath: '/deploy/'
      preLoaderRoute: typeof AppAuthDeployIndexRouteImport
      parentRoute: typeof AppAuthDeployRoute
    }
    '/_app/_auth/topics/$id': {
      id: '/_app/_auth/topics/$id'
      path: '/$id'
      fullPath: '/topics/$id'
      preLoaderRoute: typeof AppAuthTopicsIdRouteImport
      parentRoute: typeof AppAuthTopicsRoute
    }
    '/_app/_auth/resources/tunnels': {
      id: '/_app/_auth/resources/tunnels'
      path: '/resources/tunnels'
      fullPath: '/resources/tunnels'
      preLoaderRoute: typeof AppAuthResourcesTunnelsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/service-instances': {
      id: '/_app/_auth/resources/service-instances'
      path: '/resources/service-instances'
      fullPath: '/resources/service-instances'
      preLoaderRoute: typeof AppAuthResourcesServiceInstancesRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/servers': {
      id: '/_app/_auth/resources/servers'
      path: '/resources/servers'
      fullPath: '/resources/servers'
      preLoaderRoute: typeof AppAuthResourcesServersRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/scripts': {
      id: '/_app/_auth/resources/scripts'
      path: '/resources/scripts'
      fullPath: '/resources/scripts'
      preLoaderRoute: typeof AppAuthResourcesScriptsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/platform-accounts': {
      id: '/_app/_auth/resources/platform-accounts'
      path: '/resources/platform-accounts'
      fullPath: '/resources/platform-accounts'
      preLoaderRoute: typeof AppAuthResourcesPlatformAccountsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/connectors': {
      id: '/_app/_auth/resources/connectors'
      path: '/resources/connectors'
      fullPath: '/resources/connectors'
      preLoaderRoute: typeof AppAuthResourcesConnectorsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/resources/ai-providers': {
      id: '/_app/_auth/resources/ai-providers'
      path: '/resources/ai-providers'
      fullPath: '/resources/ai-providers'
      preLoaderRoute: typeof AppAuthResourcesAiProvidersRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/groups/$id': {
      id: '/_app/_auth/groups/$id'
      path: '/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AppAuthGroupsIdRouteImport
      parentRoute: typeof AppAuthGroupsRoute
    }
    '/_app/_auth/deploy/create': {
      id: '/_app/_auth/deploy/create'
      path: '/create'
      fullPath: '/deploy/create'
      preLoaderRoute: typeof AppAuthDeployCreateRouteImport
      parentRoute: typeof AppAuthDeployRoute
    }
    '/_app/_auth/apps/$appId': {
      id: '/_app/_auth/apps/$appId'
      path: '/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppAuthAppsAppIdRouteImport
      parentRoute: typeof AppAuthAppsRoute
    }
    '/_app/_auth/actions/$actionId': {
      id: '/_app/_auth/actions/$actionId'
      path: '/$actionId'
      fullPath: '/actions/$actionId'
      preLoaderRoute: typeof AppAuthActionsActionIdRouteImport
      parentRoute: typeof AppAuthActionsRoute
    }
    '/_app/_auth/_superuser/tunnels': {
      id: '/_app/_auth/_superuser/tunnels'
      path: '/tunnels'
      fullPath: '/tunnels'
      preLoaderRoute: typeof AppAuthSuperuserTunnelsRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/_superuser/system-tasks': {
      id: '/_app/_auth/_superuser/system-tasks'
      path: '/system-tasks'
      fullPath: '/system-tasks'
      preLoaderRoute: typeof AppAuthSuperuserSystemTasksRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/_superuser/status': {
      id: '/_app/_auth/_superuser/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AppAuthSuperuserStatusRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/_superuser/settings': {
      id: '/_app/_auth/_superuser/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppAuthSuperuserSettingsRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/_superuser/logs': {
      id: '/_app/_auth/_superuser/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppAuthSuperuserLogsRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/_superuser/iac': {
      id: '/_app/_auth/_superuser/iac'
      path: '/iac'
      fullPath: '/iac'
      preLoaderRoute: typeof AppAuthSuperuserIacRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/_superuser/users/': {
      id: '/_app/_auth/_superuser/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppAuthSuperuserUsersIndexRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/_superuser/terminal/': {
      id: '/_app/_auth/_superuser/terminal/'
      path: '/terminal'
      fullPath: '/terminal/'
      preLoaderRoute: typeof AppAuthSuperuserTerminalIndexRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
    '/_app/_auth/admin/credentials/env-vars': {
      id: '/_app/_auth/admin/credentials/env-vars'
      path: '/admin/credentials/env-vars'
      fullPath: '/admin/credentials/env-vars'
      preLoaderRoute: typeof AppAuthAdminCredentialsEnvVarsRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/_superuser/terminal/server/$serverId': {
      id: '/_app/_auth/_superuser/terminal/server/$serverId'
      path: '/terminal/server/$serverId'
      fullPath: '/terminal/server/$serverId'
      preLoaderRoute: typeof AppAuthSuperuserTerminalServerServerIdRouteImport
      parentRoute: typeof AppAuthSuperuserRoute
    }
  }
}

interface AppAuthSuperuserRouteChildren {
  AppAuthSuperuserIacRoute: typeof AppAuthSuperuserIacRoute
  AppAuthSuperuserLogsRoute: typeof AppAuthSuperuserLogsRoute
  AppAuthSuperuserSettingsRoute: typeof AppAuthSuperuserSettingsRoute
  AppAuthSuperuserStatusRoute: typeof AppAuthSuperuserStatusRoute
  AppAuthSuperuserSystemTasksRoute: typeof AppAuthSuperuserSystemTasksRoute
  AppAuthSuperuserTunnelsRoute: typeof AppAuthSuperuserTunnelsRoute
  AppAuthSuperuserTerminalIndexRoute: typeof AppAuthSuperuserTerminalIndexRoute
  AppAuthSuperuserUsersIndexRoute: typeof AppAuthSuperuserUsersIndexRoute
  AppAuthSuperuserTerminalServerServerIdRoute: typeof AppAuthSuperuserTerminalServerServerIdRoute
}

const AppAuthSuperuserRouteChildren: AppAuthSuperuserRouteChildren = {
  AppAuthSuperuserIacRoute: AppAuthSuperuserIacRoute,
  AppAuthSuperuserLogsRoute: AppAuthSuperuserLogsRoute,
  AppAuthSuperuserSettingsRoute: AppAuthSuperuserSettingsRoute,
  AppAuthSuperuserStatusRoute: AppAuthSuperuserStatusRoute,
  AppAuthSuperuserSystemTasksRoute: AppAuthSuperuserSystemTasksRoute,
  AppAuthSuperuserTunnelsRoute: AppAuthSuperuserTunnelsRoute,
  AppAuthSuperuserTerminalIndexRoute: AppAuthSuperuserTerminalIndexRoute,
  AppAuthSuperuserUsersIndexRoute: AppAuthSuperuserUsersIndexRoute,
  AppAuthSuperuserTerminalServerServerIdRoute:
    AppAuthSuperuserTerminalServerServerIdRoute,
}

const AppAuthSuperuserRouteWithChildren =
  AppAuthSuperuserRoute._addFileChildren(AppAuthSuperuserRouteChildren)

interface AppAuthActionsRouteChildren {
  AppAuthActionsActionIdRoute: typeof AppAuthActionsActionIdRoute
}

const AppAuthActionsRouteChildren: AppAuthActionsRouteChildren = {
  AppAuthActionsActionIdRoute: AppAuthActionsActionIdRoute,
}

const AppAuthActionsRouteWithChildren = AppAuthActionsRoute._addFileChildren(
  AppAuthActionsRouteChildren,
)

interface AppAuthAppsRouteChildren {
  AppAuthAppsAppIdRoute: typeof AppAuthAppsAppIdRoute
}

const AppAuthAppsRouteChildren: AppAuthAppsRouteChildren = {
  AppAuthAppsAppIdRoute: AppAuthAppsAppIdRoute,
}

const AppAuthAppsRouteWithChildren = AppAuthAppsRoute._addFileChildren(
  AppAuthAppsRouteChildren,
)

interface AppAuthDeployRouteChildren {
  AppAuthDeployCreateRoute: typeof AppAuthDeployCreateRoute
  AppAuthDeployIndexRoute: typeof AppAuthDeployIndexRoute
}

const AppAuthDeployRouteChildren: AppAuthDeployRouteChildren = {
  AppAuthDeployCreateRoute: AppAuthDeployCreateRoute,
  AppAuthDeployIndexRoute: AppAuthDeployIndexRoute,
}

const AppAuthDeployRouteWithChildren = AppAuthDeployRoute._addFileChildren(
  AppAuthDeployRouteChildren,
)

interface AppAuthGroupsRouteChildren {
  AppAuthGroupsIdRoute: typeof AppAuthGroupsIdRoute
  AppAuthGroupsIndexRoute: typeof AppAuthGroupsIndexRoute
}

const AppAuthGroupsRouteChildren: AppAuthGroupsRouteChildren = {
  AppAuthGroupsIdRoute: AppAuthGroupsIdRoute,
  AppAuthGroupsIndexRoute: AppAuthGroupsIndexRoute,
}

const AppAuthGroupsRouteWithChildren = AppAuthGroupsRoute._addFileChildren(
  AppAuthGroupsRouteChildren,
)

interface AppAuthTopicsRouteChildren {
  AppAuthTopicsIdRoute: typeof AppAuthTopicsIdRoute
  AppAuthTopicsIndexRoute: typeof AppAuthTopicsIndexRoute
}

const AppAuthTopicsRouteChildren: AppAuthTopicsRouteChildren = {
  AppAuthTopicsIdRoute: AppAuthTopicsIdRoute,
  AppAuthTopicsIndexRoute: AppAuthTopicsIndexRoute,
}

const AppAuthTopicsRouteWithChildren = AppAuthTopicsRoute._addFileChildren(
  AppAuthTopicsRouteChildren,
)

interface AppAuthRouteChildren {
  AppAuthSuperuserRoute: typeof AppAuthSuperuserRouteWithChildren
  AppAuthActionsRoute: typeof AppAuthActionsRouteWithChildren
  AppAuthAppsRoute: typeof AppAuthAppsRouteWithChildren
  AppAuthAuditRoute: typeof AppAuthAuditRoute
  AppAuthCertificatesRoute: typeof AppAuthCertificatesRoute
  AppAuthComponentsRoute: typeof AppAuthComponentsRoute
  AppAuthDeployRoute: typeof AppAuthDeployRouteWithChildren
  AppAuthDockerRoute: typeof AppAuthDockerRoute
  AppAuthGroupsRoute: typeof AppAuthGroupsRouteWithChildren
  AppAuthOverviewRoute: typeof AppAuthOverviewRoute
  AppAuthProfileRoute: typeof AppAuthProfileRoute
  AppAuthSecretsRoute: typeof AppAuthSecretsRoute
  AppAuthSharedEnvsRoute: typeof AppAuthSharedEnvsRoute
  AppAuthSpaceRoute: typeof AppAuthSpaceRoute
  AppAuthTopicsRoute: typeof AppAuthTopicsRouteWithChildren
  AppAuthResourcesAiProvidersRoute: typeof AppAuthResourcesAiProvidersRoute
  AppAuthResourcesConnectorsRoute: typeof AppAuthResourcesConnectorsRoute
  AppAuthResourcesPlatformAccountsRoute: typeof AppAuthResourcesPlatformAccountsRoute
  AppAuthResourcesScriptsRoute: typeof AppAuthResourcesScriptsRoute
  AppAuthResourcesServersRoute: typeof AppAuthResourcesServersRoute
  AppAuthResourcesServiceInstancesRoute: typeof AppAuthResourcesServiceInstancesRoute
  AppAuthResourcesTunnelsRoute: typeof AppAuthResourcesTunnelsRoute
  AppAuthResourcesIndexRoute: typeof AppAuthResourcesIndexRoute
  AppAuthStoreIndexRoute: typeof AppAuthStoreIndexRoute
  AppAuthAdminCredentialsEnvVarsRoute: typeof AppAuthAdminCredentialsEnvVarsRoute
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthSuperuserRoute: AppAuthSuperuserRouteWithChildren,
  AppAuthActionsRoute: AppAuthActionsRouteWithChildren,
  AppAuthAppsRoute: AppAuthAppsRouteWithChildren,
  AppAuthAuditRoute: AppAuthAuditRoute,
  AppAuthCertificatesRoute: AppAuthCertificatesRoute,
  AppAuthComponentsRoute: AppAuthComponentsRoute,
  AppAuthDeployRoute: AppAuthDeployRouteWithChildren,
  AppAuthDockerRoute: AppAuthDockerRoute,
  AppAuthGroupsRoute: AppAuthGroupsRouteWithChildren,
  AppAuthOverviewRoute: AppAuthOverviewRoute,
  AppAuthProfileRoute: AppAuthProfileRoute,
  AppAuthSecretsRoute: AppAuthSecretsRoute,
  AppAuthSharedEnvsRoute: AppAuthSharedEnvsRoute,
  AppAuthSpaceRoute: AppAuthSpaceRoute,
  AppAuthTopicsRoute: AppAuthTopicsRouteWithChildren,
  AppAuthResourcesAiProvidersRoute: AppAuthResourcesAiProvidersRoute,
  AppAuthResourcesConnectorsRoute: AppAuthResourcesConnectorsRoute,
  AppAuthResourcesPlatformAccountsRoute: AppAuthResourcesPlatformAccountsRoute,
  AppAuthResourcesScriptsRoute: AppAuthResourcesScriptsRoute,
  AppAuthResourcesServersRoute: AppAuthResourcesServersRoute,
  AppAuthResourcesServiceInstancesRoute: AppAuthResourcesServiceInstancesRoute,
  AppAuthResourcesTunnelsRoute: AppAuthResourcesTunnelsRoute,
  AppAuthResourcesIndexRoute: AppAuthResourcesIndexRoute,
  AppAuthStoreIndexRoute: AppAuthStoreIndexRoute,
  AppAuthAdminCredentialsEnvVarsRoute: AppAuthAdminCredentialsEnvVarsRoute,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppResetPasswordRoute: typeof AppResetPasswordRoute
  AppSetupRoute: typeof AppSetupRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppResetPasswordRoute: AppResetPasswordRoute,
  AppSetupRoute: AppSetupRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ShareTopicTokenRoute: ShareTopicTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
